// Regenerates src/icons.ts: fetches meteocons (fill variant) and inlines each as
// a base64 data URI so the card ships as one self-contained asset (no runtime CDN).
// Run: node tools/gen-icons.mjs
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const base = "https://cdn.jsdelivr.net/npm/@bybas/weather-icons@2.0.0/production/fill/all";

// HA condition slug -> meteocons filename (fill variant).
const MAP = {
  "clear-night": "clear-night",
  cloudy: "overcast",
  fog: "fog",
  hail: "hail",
  lightning: "thunderstorms",
  "lightning-rainy": "thunderstorms-rain",
  partlycloudy: "partly-cloudy-day",
  pouring: "rain",
  rainy: "rain",
  snowy: "snow",
  "snowy-rainy": "sleet",
  sunny: "clear-day",
  windy: "wind",
  "windy-variant": "wind",
  exceptional: "not-available",
};

const files = [...new Set(Object.values(MAP))];
const uris = {};
for (const f of files) {
  const r = await fetch(`${base}/${f}.svg`);
  if (!r.ok) throw new Error(`${f}: ${r.status}`);
  const svg = await r.text();
  uris[f] = "data:image/svg+xml;base64," + Buffer.from(svg, "utf8").toString("base64");
}

let out = "";
out += "// Meteocons, fill variant (github.com/basmilius/weather-icons, MIT), inlined as\n";
out += "// data URIs so the card stays one self-contained asset with no runtime CDN.\n";
out += "// Generated by tools/gen-icons.mjs — edit the map there, not here.\n\n";
out += "// prettier-ignore\n";
out += "const SVG: Record<string, string> = {\n";
for (const f of files) out += `  ${JSON.stringify(f)}: ${JSON.stringify(uris[f])},\n`;
out += "};\n\n";
out += "/** HA weather condition slug -> ECharts `image://` symbol (meteocons fill). */\n";
out += "export const ICONS: Record<string, string> = {\n";
for (const [cond, f] of Object.entries(MAP)) {
  out += `  ${JSON.stringify(cond)}: "image://" + SVG[${JSON.stringify(f)}],\n`;
}
out += "};\n";

const dir = path.dirname(fileURLToPath(import.meta.url));
const dest = path.join(dir, "..", "src", "icons.ts");
fs.writeFileSync(dest, out);
console.log("wrote", dest, "-", files.length, "icons,", out.length, "bytes");
